name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: sudo apt update; sudo apt install libsdl2-dev libffi-dev
    - name: make
      run: cd tulip/linux; ./build.sh
