name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
    - uses: Homebrew/actions/setup-homebrew@master
      id: set-up-homebrew
    - name: make
      run: brew install pkg-config libffi; cd tulip/macos; ./build.sh
